### ISSUE TITLE
Implement the BufferPool constructor and the getPage() method. 

### ISSUE THREAD

**Issue by RosaGeorge31** [ishaan-6298/SimpleDB#5]
In order to complete the BufferPool.java class the constructor and the BufferPool.getPage() needs to be implemented. The method getPage() will be used by the SeqScan operator. The functionality of getPage() will be tested in the implementation of HeapFile and hence we need to also complete that in order to ensure that the method is giving the desired output.

**Comment by salman-bhai** [comment]
Add Description for this as well!
